services:
  - type: web
    name: tubeflow-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NPM_FLAGS
        value: --unsafe-perm
    buildpacks:
      - node
      - ffmpeg

